// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A9TwJkvnr1qBmEVMv-ZyWnlrdYoROdU',
    appId: '1:74644851568:web:fc88e0b2d7f99125349db5',
    messagingSenderId: '74644851568',
    projectId: 'todo-list-d273c',
    authDomain: 'todo-list-d273c.firebaseapp.com',
    storageBucket: 'todo-list-d273c.appspot.com',
    measurementId: 'G-WEP65LY21C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rZilMCHz7a5-yMAS77xMhsCfMqwKtFI',
    appId: '1:74644851568:ios:f40456d7d3076662349db5',
    messagingSenderId: '74644851568',
    projectId: 'todo-list-d273c',
    storageBucket: 'todo-list-d273c.appspot.com',
    iosClientId: '74644851568-bbh2jhjh1eimc617f6rdk28p622ouegq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sferaProject1',
  );
}
